//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BliksemWP.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BliksemWP.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string DownloadUpdatePage_Apply {
            get {
                return ResourceManager.GetString("DownloadUpdatePage_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        public static string DownloadUpdatePage_Downloading {
            get {
                return ResourceManager.GetString("DownloadUpdatePage_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated.
        /// </summary>
        public static string DownloadUpdatePage_LastUpdate {
            get {
                return ResourceManager.GetString("DownloadUpdatePage_LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to region.
        /// </summary>
        public static string DownloadUpdatePage_Title {
            get {
                return ResourceManager.GetString("DownloadUpdatePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is being updated.
        /// </summary>
        public static string DownloadUpdatePage_UpdateInProgress {
            get {
                return ResourceManager.GetString("DownloadUpdatePage_UpdateInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLIKSEM.
        /// </summary>
        public static string General_AppTitle {
            get {
                return ResourceManager.GetString("General_AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus.
        /// </summary>
        public static string General_JourneyLegType_Bus {
            get {
                return ResourceManager.GetString("General_JourneyLegType_Bus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subway.
        /// </summary>
        public static string General_JourneyLegType_Subway {
            get {
                return ResourceManager.GetString("General_JourneyLegType_Subway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tram.
        /// </summary>
        public static string General_JourneyLegType_Tram {
            get {
                return ResourceManager.GetString("General_JourneyLegType_Tram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string General_ResourceFlowDirection {
            get {
                return ResourceManager.GetString("General_ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string General_ResourceLanguage {
            get {
                return ResourceManager.GetString("General_ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string InfoAndSettingsPage_Contact_ContactButton {
            get {
                return ResourceManager.GetString("InfoAndSettingsPage_Contact_ContactButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string InfoAndSettingsPage_Contact_Header {
            get {
                return ResourceManager.GetString("InfoAndSettingsPage_Contact_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback Bliksem WP app.
        /// </summary>
        public static string InfoAndSettingsPage_Contact_MailSubject {
            get {
                return ResourceManager.GetString("InfoAndSettingsPage_Contact_MailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string InfoAndSettingsPage_Contact_ReviewButton {
            get {
                return ResourceManager.GetString("InfoAndSettingsPage_Contact_ReviewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have questions, comments or suggestions, we would like to receive this by e-mail. We also ask you to review this app. Thank you!.
        /// </summary>
        public static string InfoAndSettingsPage_Contact_Text {
            get {
                return ResourceManager.GetString("InfoAndSettingsPage_Contact_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        public static string InfoAndSettingsPage_Disclaimer_Header {
            get {
                return ResourceManager.GetString("InfoAndSettingsPage_Disclaimer_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We pay the utmost care and attention to this app and the data. Nevertheless, errors or omissions occur. We accept no liability for damage caused by these errors or omissions..
        /// </summary>
        public static string InfoAndSettingsPage_Disclaimer_Text {
            get {
                return ResourceManager.GetString("InfoAndSettingsPage_Disclaimer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2014 Bliksem Labs.
        /// </summary>
        public static string InfoAndSettingsPage_Info_Copyright {
            get {
                return ResourceManager.GetString("InfoAndSettingsPage_Info_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string InfoAndSettingsPage_Info_Header {
            get {
                return ResourceManager.GetString("InfoAndSettingsPage_Info_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bliksem is an implementation of a new routing algorithm by Microsoft, that enables us to plan your route offline and on your phone. Offline has advantages because you&apos;ll always have your schedules with you, ensuring continuity and privacy..
        /// </summary>
        public static string InfoAndSettingsPage_Info_Message {
            get {
                return ResourceManager.GetString("InfoAndSettingsPage_Info_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string InfoAndSettingsPage_Info_Version {
            get {
                return ResourceManager.GetString("InfoAndSettingsPage_Info_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string InfoAndSettingsPage_Privacy_Header {
            get {
                return ResourceManager.GetString("InfoAndSettingsPage_Privacy_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application uses an internet connection to update the timetable. The application will never ask for your location .
        /// </summary>
        public static string InfoAndSettingsPage_Privacy_Text {
            get {
                return ResourceManager.GetString("InfoAndSettingsPage_Privacy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement.
        /// </summary>
        public static string InfoAndSettingsPage_Privacy_Title {
            get {
                return ResourceManager.GetString("InfoAndSettingsPage_Privacy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string InfoAndSettingsPage_Settings_Header {
            get {
                return ResourceManager.GetString("InfoAndSettingsPage_Settings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string JourneyLegControl_Change {
            get {
                return ResourceManager.GetString("JourneyLegControl_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading.
        /// </summary>
        public static string JourneyLegControl_Direction {
            get {
                return ResourceManager.GetString("JourneyLegControl_Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walk.
        /// </summary>
        public static string JourneyLegControl_Walk {
            get {
                return ResourceManager.GetString("JourneyLegControl_Walk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose region.
        /// </summary>
        public static string MainPage_AppBar_ChangeRegion {
            get {
                return ResourceManager.GetString("MainPage_AppBar_ChangeRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info and settings.
        /// </summary>
        public static string MainPage_AppBar_Info {
            get {
                return ResourceManager.GetString("MainPage_AppBar_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan!.
        /// </summary>
        public static string MainPage_Calculate {
            get {
                return ResourceManager.GetString("MainPage_Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string MainPage_Date {
            get {
                return ResourceManager.GetString("MainPage_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a departure and destination point.
        /// </summary>
        public static string MainPage_Error_ChooseStops {
            get {
                return ResourceManager.GetString("MainPage_Error_ChooseStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string MainPage_From {
            get {
                return ResourceManager.GetString("MainPage_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrive by.
        /// </summary>
        public static string MainPage_GivenTimeIsArrival {
            get {
                return ResourceManager.GetString("MainPage_GivenTimeIsArrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depart at.
        /// </summary>
        public static string MainPage_GivenTimeIsDeparture {
            get {
                return ResourceManager.GetString("MainPage_GivenTimeIsDeparture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string MainPage_Region {
            get {
                return ResourceManager.GetString("MainPage_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string MainPage_Time {
            get {
                return ResourceManager.GetString("MainPage_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trip planner.
        /// </summary>
        public static string MainPage_Title {
            get {
                return ResourceManager.GetString("MainPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string MainPage_To {
            get {
                return ResourceManager.GetString("MainPage_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update data.
        /// </summary>
        public static string MainPage_Update {
            get {
                return ResourceManager.GetString("MainPage_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to calendar.
        /// </summary>
        public static string ResultPage_AddToCalendarButton {
            get {
                return ResourceManager.GetString("ResultPage_AddToCalendarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string ResultPage_ShareButton {
            get {
                return ResourceManager.GetString("ResultPage_ShareButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRAVEL OPTIONS.
        /// </summary>
        public static string ResultPage_Title {
            get {
                return ResourceManager.GetString("ResultPage_Title", resourceCulture);
            }
        }
    }
}
