//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BliksemWP.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BliksemWP.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update.
        /// </summary>
        public static string DownloadUpdatePage_Title {
            get {
                return ResourceManager.GetString("DownloadUpdatePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data wordt geüpdatet.
        /// </summary>
        public static string DownloadUpdatePage_UpdateInProgress {
            get {
                return ResourceManager.GetString("DownloadUpdatePage_UpdateInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLIKSEM.
        /// </summary>
        public static string General_AppTitle {
            get {
                return ResourceManager.GetString("General_AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus.
        /// </summary>
        public static string General_JourneyLegType_Bus {
            get {
                return ResourceManager.GetString("General_JourneyLegType_Bus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metro.
        /// </summary>
        public static string General_JourneyLegType_Subway {
            get {
                return ResourceManager.GetString("General_JourneyLegType_Subway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tram.
        /// </summary>
        public static string General_JourneyLegType_Tram {
            get {
                return ResourceManager.GetString("General_JourneyLegType_Tram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string General_ResourceFlowDirection {
            get {
                return ResourceManager.GetString("General_ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string General_ResourceLanguage {
            get {
                return ResourceManager.GetString("General_ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overstap.
        /// </summary>
        public static string JourneyLegControl_Change {
            get {
                return ResourceManager.GetString("JourneyLegControl_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Richting:.
        /// </summary>
        public static string JourneyLegControl_Direction {
            get {
                return ResourceManager.GetString("JourneyLegControl_Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop.
        /// </summary>
        public static string JourneyLegControl_Walk {
            get {
                return ResourceManager.GetString("JourneyLegControl_Walk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan!.
        /// </summary>
        public static string MainPage_Calculate {
            get {
                return ResourceManager.GetString("MainPage_Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string MainPage_Date {
            get {
                return ResourceManager.GetString("MainPage_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies eerst een vertrek- en eindpunt.
        /// </summary>
        public static string MainPage_Error_ChooseStops {
            get {
                return ResourceManager.GetString("MainPage_Error_ChooseStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Van.
        /// </summary>
        public static string MainPage_From {
            get {
                return ResourceManager.GetString("MainPage_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aankomst.
        /// </summary>
        public static string MainPage_GivenTimeIsArrival {
            get {
                return ResourceManager.GetString("MainPage_GivenTimeIsArrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertrek.
        /// </summary>
        public static string MainPage_GivenTimeIsDeparture {
            get {
                return ResourceManager.GetString("MainPage_GivenTimeIsDeparture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tijd.
        /// </summary>
        public static string MainPage_Time {
            get {
                return ResourceManager.GetString("MainPage_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reisplanner.
        /// </summary>
        public static string MainPage_Title {
            get {
                return ResourceManager.GetString("MainPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naar.
        /// </summary>
        public static string MainPage_To {
            get {
                return ResourceManager.GetString("MainPage_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laad nieuwe data.
        /// </summary>
        public static string MainPage_Update {
            get {
                return ResourceManager.GetString("MainPage_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voeg toe aan agenda.
        /// </summary>
        public static string ResultPage_AddToCalendarButton {
            get {
                return ResourceManager.GetString("ResultPage_AddToCalendarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deel.
        /// </summary>
        public static string ResultPage_ShareButton {
            get {
                return ResourceManager.GetString("ResultPage_ShareButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REISMOGELIJKHEDEN.
        /// </summary>
        public static string ResultPage_Title {
            get {
                return ResourceManager.GetString("ResultPage_Title", resourceCulture);
            }
        }
    }
}
